### ISSUE TITLE
Remove event listeners and stop timers when component unmounts

### ISSUE THREAD

**Issue by artem-russkikh** [notlose/react-native-spring-carousel#1]
Good work!

I'm notice that after unmount Carousel tries update scrollPanel props and this cause an error.

May be fixed by

``` javascript
componentWillUnmount: function() {
  // clearTimeout(this.timer_id);
  // clearTimeout(this.timer_id2);
  this._scrollSpring.removeAllListeners();
},

```

**Comment by notlose** [comment]
thanks @artem-russkikh ! i have added your code in the new release.

**Comment by artem-russkikh** [comment]
@notlose also add at componentWillUnmount https://github.com/notlose/react-native-spring-carousel/blob/master/index.js#L22

```
    if(timer){
      clearTimeout(timer);
    }
```

**Comment by notlose** [comment]
added code, thanks for support!
