### ISSUE TITLE
Carousel doesn't adjust its size upon transition from portrait to landscape or vice versa

### ISSUE THREAD

**Issue by umair-khan1993** [notlose/react-native-spring-carousel#2]
The only parameter carousel accepting is height/width and these parameters doesn't get updated when device is flipped. Can't this problem be fixed using flex?

**Comment by notlose** [comment]
sorry, the plugin didn't listen to device orientation change currently, and i the the height need to be re-calculated after flip, flex cannot solve the problem, maybe you can try to use this plugin
https://www.npmjs.com/package/react-native-orientation
to update the width and height
